# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
 config.vm.box = "debian/bookworm64"
 config.vm.network "forwarded_port", guest:80, host:80
 config.vm.synced_folder "htdocs", "/var/www/webRafa.127.0.0.1.nip.io/html"
 config.vm.provision "shell", inline: <<-SHELL
 apt-get update
 apt-get install -y apache2
 cp -v /vagrant/apache2.conf /etc/apache2
 cp -v /vagrant/webRafa.127.0.0.1.nip.io.conf /etc/apache2/sites-avaiable
 mkdir -p /var/www/webRafa.127.0.0.1.nip.io/html
 a2ensite webRafa.127.0.0.1.nip.io
 systemctl restart apache2
 SHELL
end
